//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.9
//
// <auto-generated>
//
// Generated from file `Murmur.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package net.mstjr.murmur.exceptions.invalid;

import net.mstjr.murmur.exceptions.MurmurException;

/**
 * This is thrown when you try to do an operation on a server that does not exist. This may happen if someone has removed the server.
 **/
public class InvalidServerException extends MurmurException
{
    public InvalidServerException()
    {
        super();
    }

    public InvalidServerException(Throwable cause)
    {
        super(cause);
    }

    public String ice_id()
    {
        return "::Murmur::InvalidServerException";
    }

    /** @hidden */
    @Override
    protected void _writeImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice("::Murmur::InvalidServerException", -1, false);
        ostr_.endSlice();
        super._writeImpl(ostr_);
    }

    /** @hidden */
    @Override
    protected void _readImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        istr_.endSlice();
        super._readImpl(istr_);
    }

    /** @hidden */
    public static final long serialVersionUID = -1095805404L;
}
