//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.9
//
// <auto-generated>
//
// Generated from file `Murmur.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package net.mstjr.murmur.exceptions.invalid;

import net.mstjr.murmur.exceptions.MurmurException;

/**
 * This is thrown when you specify an invalid userid.
 **/
public class InvalidUserException extends MurmurException
{
    public InvalidUserException()
    {
        super();
    }

    public InvalidUserException(Throwable cause)
    {
        super(cause);
    }

    public String ice_id()
    {
        return "::Murmur::InvalidUserException";
    }

    /** @hidden */
    @Override
    protected void _writeImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice("::Murmur::InvalidUserException", -1, false);
        ostr_.endSlice();
        super._writeImpl(ostr_);
    }

    /** @hidden */
    @Override
    protected void _readImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        istr_.endSlice();
        super._readImpl(istr_);
    }

    /** @hidden */
    public static final long serialVersionUID = 1609616944L;
}
