//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.9
//
// <auto-generated>
//
// Generated from file `Murmur.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package net.mstjr.murmur.permissions;

/**
 * Link this channel. You need this permission in both the source and destination channel to link channels, or in either channel to unlink them.
 **/
public interface PermissionLinkChannel
{
    int value = 128;
}
