//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.9
//
// <auto-generated>
//
// Generated from file `Murmur.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package net.mstjr.murmur.permissions;

/**
 * Whisper to channel. This is different from Speak, so you can set up different permissions.
 **/
public interface PermissionWhisper
{
    int value = 256;
}
