//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.9
//
// <auto-generated>
//
// Generated from file `Murmur.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package net.mstjr.murmur.permissions;

/**
 * Move users from channel. You need this permission in both the source and destination channel to move another user.
 **/
public interface PermissionMove
{
    int value = 32;
}
