//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.9
//
// <auto-generated>
//
// Generated from file `Murmur.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package net.mstjr.murmur.proxy.server.users;

/**
 * Reset the comment or avatar of a user. Only valid on root channel.
 **/
public interface ResetUserContent
{
    int value = 1048576;
}
