//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.9
//
// <auto-generated>
//
// Generated from file `Murmur.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package net.mstjr.murmur.logging;

/**
 * Helper class for marshaling/unmarshaling LogList.
 **/
public final class LogListHelper
{
    public static void write(com.zeroc.Ice.OutputStream ostr, LogEntry[] v)
    {
        if(v == null)
        {
            ostr.writeSize(0);
        }
        else
        {
            ostr.writeSize(v.length);
            for(int i0 = 0; i0 < v.length; i0++)
            {
                LogEntry.ice_write(ostr, v[i0]);
            }
        }
    }

    public static LogEntry[] read(com.zeroc.Ice.InputStream istr)
    {
        final LogEntry[] v;
        final int len0 = istr.readAndCheckSeqSize(5);
        v = new LogEntry[len0];
        for(int i0 = 0; i0 < len0; i0++)
        {
            v[i0] = LogEntry.ice_read(istr);
        }
        return v;
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<LogEntry[]> v)
    {
        if(v != null && v.isPresent())
        {
            write(ostr, tag, v.get());
        }
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, LogEntry[] v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            LogListHelper.write(ostr, v);
            ostr.endSize(pos);
        }
    }

    public static java.util.Optional<LogEntry[]> read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            LogEntry[] v;
            v = LogListHelper.read(istr);
            return java.util.Optional.of(v);
        }
        else
        {
            return java.util.Optional.empty();
        }
    }
}
