//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.9
//
// <auto-generated>
//
// Generated from file `Murmur.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package net.mstjr.murmur.prxl;

import net.mstjr.murmur.prx.ServerAuthenticatorPrx;

/**
 * @hidden
 */
public class _ServerAuthenticatorPrxI extends com.zeroc.Ice._ObjectPrxI implements ServerAuthenticatorPrx {
    /**
     * @hidden
     */
    public static final long serialVersionUID = 0L;
}
