//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.9
//
// <auto-generated>
//
// Generated from file `Murmur.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package net.mstjr.murmur.prxl;

import net.mstjr.murmur.prx.ServerPrx;

/** @hidden */
public class _ServerPrxI extends com.zeroc.Ice._ObjectPrxI implements ServerPrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
