//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.9
//
// <auto-generated>
//
// Generated from file `Murmur.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package net.mstjr.murmur.prx;

import net.mstjr.murmur.proxy.Meta;
import net.mstjr.murmur.proxy.callback.ServerCallback;
import net.mstjr.murmur.prxl._MetaCallbackPrxI;

/**
 * Callback interface for Meta. You can supply an implementation of this to receive notifications
 * when servers are stopped or started.
 * If an added callback ever throws an exception or goes away, it will be automatically removed.
 * Please note that all callbacks are done asynchronously; murmur does not wait for the callback to
 * complete before continuing processing.
 *
 * @see ServerCallback
 * @see Meta.addCallback
 **/
public interface MetaCallbackPrx extends com.zeroc.Ice.ObjectPrx {
    /**
     * Called when a server is started. The server is up and running when this event is sent, so all methods that
     * need a running server will work.
     *
     * @param srv Interface for started server.
     **/
    default void started(ServerPrx srv) {
        started(srv, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    /**
     * Called when a server is started. The server is up and running when this event is sent, so all methods that
     * need a running server will work.
     *
     * @param srv     Interface for started server.
     * @param context The Context map to send with the invocation.
     **/
    default void started(ServerPrx srv, java.util.Map<String, String> context) {
        _iceI_startedAsync(srv, context, true).waitForResponse();
    }

    /**
     * Called when a server is started. The server is up and running when this event is sent, so all methods that
     * need a running server will work.
     *
     * @param srv Interface for started server.
     * @return A future that will be completed when the invocation completes.
     **/
    default java.util.concurrent.CompletableFuture<Void> startedAsync(ServerPrx srv) {
        return _iceI_startedAsync(srv, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    /**
     * Called when a server is started. The server is up and running when this event is sent, so all methods that
     * need a running server will work.
     *
     * @param srv     Interface for started server.
     * @param context The Context map to send with the invocation.
     * @return A future that will be completed when the invocation completes.
     **/
    default java.util.concurrent.CompletableFuture<Void> startedAsync(ServerPrx srv, java.util.Map<String, String> context) {
        return _iceI_startedAsync(srv, context, false);
    }

    /**
     * @param iceP_srv -
     * @param context  -
     * @param sync     -
     * @return -
     * @hidden
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_startedAsync(ServerPrx iceP_srv, java.util.Map<String, String> context, boolean sync) {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "started", null, sync, null);
        f.invoke(false, context, null, ostr -> {
            ostr.writeProxy(iceP_srv);
        }, null);
        return f;
    }

    /**
     * Called when a server is stopped. The server is already stopped when this event is sent, so no methods that
     * need a running server will work.
     *
     * @param srv Interface for started server.
     **/
    default void stopped(ServerPrx srv) {
        stopped(srv, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    /**
     * Called when a server is stopped. The server is already stopped when this event is sent, so no methods that
     * need a running server will work.
     *
     * @param srv     Interface for started server.
     * @param context The Context map to send with the invocation.
     **/
    default void stopped(ServerPrx srv, java.util.Map<String, String> context) {
        _iceI_stoppedAsync(srv, context, true).waitForResponse();
    }

    /**
     * Called when a server is stopped. The server is already stopped when this event is sent, so no methods that
     * need a running server will work.
     *
     * @param srv Interface for started server.
     * @return A future that will be completed when the invocation completes.
     **/
    default java.util.concurrent.CompletableFuture<Void> stoppedAsync(ServerPrx srv) {
        return _iceI_stoppedAsync(srv, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    /**
     * Called when a server is stopped. The server is already stopped when this event is sent, so no methods that
     * need a running server will work.
     *
     * @param srv     Interface for started server.
     * @param context The Context map to send with the invocation.
     * @return A future that will be completed when the invocation completes.
     **/
    default java.util.concurrent.CompletableFuture<Void> stoppedAsync(ServerPrx srv, java.util.Map<String, String> context) {
        return _iceI_stoppedAsync(srv, context, false);
    }

    /**
     * @param iceP_srv -
     * @param context  -
     * @param sync     -
     * @return -
     * @hidden
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_stoppedAsync(ServerPrx iceP_srv, java.util.Map<String, String> context, boolean sync) {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "stopped", null, sync, null);
        f.invoke(false, context, null, ostr -> {
            ostr.writeProxy(iceP_srv);
        }, null);
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     *
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static MetaCallbackPrx checkedCast(com.zeroc.Ice.ObjectPrx obj) {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), MetaCallbackPrx.class, _MetaCallbackPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     *
     * @param obj     The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static MetaCallbackPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context) {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), MetaCallbackPrx.class, _MetaCallbackPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     *
     * @param obj   The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static MetaCallbackPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet) {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), MetaCallbackPrx.class, _MetaCallbackPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     *
     * @param obj     The untyped proxy.
     * @param facet   The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static MetaCallbackPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context) {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), MetaCallbackPrx.class, _MetaCallbackPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     *
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static MetaCallbackPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj) {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, MetaCallbackPrx.class, _MetaCallbackPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     *
     * @param obj   The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static MetaCallbackPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet) {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, MetaCallbackPrx.class, _MetaCallbackPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     *
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default MetaCallbackPrx ice_context(java.util.Map<String, String> newContext) {
        return (MetaCallbackPrx) _ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     *
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default MetaCallbackPrx ice_adapterId(String newAdapterId) {
        return (MetaCallbackPrx) _ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     *
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default MetaCallbackPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints) {
        return (MetaCallbackPrx) _ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     *
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default MetaCallbackPrx ice_locatorCacheTimeout(int newTimeout) {
        return (MetaCallbackPrx) _ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     *
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default MetaCallbackPrx ice_invocationTimeout(int newTimeout) {
        return (MetaCallbackPrx) _ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     *
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default MetaCallbackPrx ice_connectionCached(boolean newCache) {
        return (MetaCallbackPrx) _ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     *
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default MetaCallbackPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType) {
        return (MetaCallbackPrx) _ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     *
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     *          used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     *          insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default MetaCallbackPrx ice_secure(boolean b) {
        return (MetaCallbackPrx) _ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     *
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default MetaCallbackPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e) {
        return (MetaCallbackPrx) _ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     *
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     *          and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     *          <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default MetaCallbackPrx ice_preferSecure(boolean b) {
        return (MetaCallbackPrx) _ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     *
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default MetaCallbackPrx ice_router(com.zeroc.Ice.RouterPrx router) {
        return (MetaCallbackPrx) _ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     *
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default MetaCallbackPrx ice_locator(com.zeroc.Ice.LocatorPrx locator) {
        return (MetaCallbackPrx) _ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     *
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default MetaCallbackPrx ice_collocationOptimized(boolean b) {
        return (MetaCallbackPrx) _ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     *
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default MetaCallbackPrx ice_twoway() {
        return (MetaCallbackPrx) _ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     *
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default MetaCallbackPrx ice_oneway() {
        return (MetaCallbackPrx) _ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     *
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default MetaCallbackPrx ice_batchOneway() {
        return (MetaCallbackPrx) _ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     *
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default MetaCallbackPrx ice_datagram() {
        return (MetaCallbackPrx) _ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     *
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default MetaCallbackPrx ice_batchDatagram() {
        return (MetaCallbackPrx) _ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     *
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default MetaCallbackPrx ice_compress(boolean co) {
        return (MetaCallbackPrx) _ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     *
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default MetaCallbackPrx ice_timeout(int t) {
        return (MetaCallbackPrx) _ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     *
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default MetaCallbackPrx ice_connectionId(String connectionId) {
        return (MetaCallbackPrx) _ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     *
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default MetaCallbackPrx ice_fixed(com.zeroc.Ice.Connection connection) {
        return (MetaCallbackPrx) _ice_fixed(connection);
    }

    static String ice_staticId() {
        return "::Murmur::MetaCallback";
    }
}
