//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.9
//
// <auto-generated>
//
// Generated from file `Murmur.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package net.mstjr.murmur.prx;

import net.mstjr.murmur.helpers.NameMapHelper;
import net.mstjr.murmur.proxy.server.Server;
import net.mstjr.murmur.proxy.server.users.UserInfo;
import net.mstjr.murmur.helpers.UserInfoMapHelper;
import net.mstjr.murmur.prxl._ServerUpdatingAuthenticatorPrxI;

/**
 * Callback interface for server authentication and registration. This allows you to support both authentication
 * and account updating.
 * You do not need to implement this if all you want is authentication, you only need this if other scripts
 * connected to the same server calls e.g. {@link Server.setTexture}.
 * Almost all of these methods support fall through, meaning murmur should continue the operation against its
 * own database.
 **/
public interface ServerUpdatingAuthenticatorPrx extends ServerAuthenticatorPrx
{
    /**
     * Register a new user.
     * @param info Information about user to register.
     * @return User id of new user, -1 for registration failure, or -2 to fall through.
     **/
    default int registerUser(java.util.Map<UserInfo, String> info)
    {
        return registerUser(info, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    /**
     * Register a new user.
     * @param info Information about user to register.
     * @param context The Context map to send with the invocation.
     * @return User id of new user, -1 for registration failure, or -2 to fall through.
     **/
    default int registerUser(java.util.Map<UserInfo, String> info, java.util.Map<String, String> context)
    {
        return _iceI_registerUserAsync(info, context, true).waitForResponse();
    }

    /**
     * Register a new user.
     * @param info Information about user to register.
     * @return User id of new user, -1 for registration failure, or -2 to fall through.
     **/
    default java.util.concurrent.CompletableFuture<Integer> registerUserAsync(java.util.Map<UserInfo, String> info)
    {
        return _iceI_registerUserAsync(info, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    /**
     * Register a new user.
     * @param info Information about user to register.
     * @param context The Context map to send with the invocation.
     * @return User id of new user, -1 for registration failure, or -2 to fall through.
     **/
    default java.util.concurrent.CompletableFuture<Integer> registerUserAsync(java.util.Map<UserInfo, String> info, java.util.Map<String, String> context)
    {
        return _iceI_registerUserAsync(info, context, false);
    }

    /**
     * @hidden
     * @param iceP_info -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Integer> _iceI_registerUserAsync(java.util.Map<UserInfo, String> iceP_info, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Integer> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "registerUser", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     UserInfoMapHelper.write(ostr, iceP_info);
                 }, istr -> {
                     int ret;
                     ret = istr.readInt();
                     return ret;
                 });
        return f;
    }

    /**
     * Unregister a user.
     * @param id Userid to unregister.
     * @return 1 for successful unregistration, 0 for unsuccessful unregistration, -1 to fall through.
     **/
    default int unregisterUser(int id)
    {
        return unregisterUser(id, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    /**
     * Unregister a user.
     * @param id Userid to unregister.
     * @param context The Context map to send with the invocation.
     * @return 1 for successful unregistration, 0 for unsuccessful unregistration, -1 to fall through.
     **/
    default int unregisterUser(int id, java.util.Map<String, String> context)
    {
        return _iceI_unregisterUserAsync(id, context, true).waitForResponse();
    }

    /**
     * Unregister a user.
     * @param id Userid to unregister.
     * @return 1 for successful unregistration, 0 for unsuccessful unregistration, -1 to fall through.
     **/
    default java.util.concurrent.CompletableFuture<Integer> unregisterUserAsync(int id)
    {
        return _iceI_unregisterUserAsync(id, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    /**
     * Unregister a user.
     * @param id Userid to unregister.
     * @param context The Context map to send with the invocation.
     * @return 1 for successful unregistration, 0 for unsuccessful unregistration, -1 to fall through.
     **/
    default java.util.concurrent.CompletableFuture<Integer> unregisterUserAsync(int id, java.util.Map<String, String> context)
    {
        return _iceI_unregisterUserAsync(id, context, false);
    }

    /**
     * @hidden
     * @param iceP_id -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Integer> _iceI_unregisterUserAsync(int iceP_id, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Integer> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "unregisterUser", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeInt(iceP_id);
                 }, istr -> {
                     int ret;
                     ret = istr.readInt();
                     return ret;
                 });
        return f;
    }

    /**
     * Get a list of registered users matching filter.
     * @param filter Substring usernames must contain. If empty, return all registered users.
     * @return List of matching registered users.
     **/
    default java.util.Map<Integer, String> getRegisteredUsers(String filter)
    {
        return getRegisteredUsers(filter, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    /**
     * Get a list of registered users matching filter.
     * @param filter Substring usernames must contain. If empty, return all registered users.
     * @param context The Context map to send with the invocation.
     * @return List of matching registered users.
     **/
    default java.util.Map<Integer, String> getRegisteredUsers(String filter, java.util.Map<String, String> context)
    {
        return _iceI_getRegisteredUsersAsync(filter, context, true).waitForResponse();
    }

    /**
     * Get a list of registered users matching filter.
     * @param filter Substring usernames must contain. If empty, return all registered users.
     * @return List of matching registered users.
     **/
    default java.util.concurrent.CompletableFuture<java.util.Map<Integer, String>> getRegisteredUsersAsync(String filter)
    {
        return _iceI_getRegisteredUsersAsync(filter, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    /**
     * Get a list of registered users matching filter.
     * @param filter Substring usernames must contain. If empty, return all registered users.
     * @param context The Context map to send with the invocation.
     * @return List of matching registered users.
     **/
    default java.util.concurrent.CompletableFuture<java.util.Map<Integer, String>> getRegisteredUsersAsync(String filter, java.util.Map<String, String> context)
    {
        return _iceI_getRegisteredUsersAsync(filter, context, false);
    }

    /**
     * @hidden
     * @param iceP_filter -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.util.Map<Integer, String>> _iceI_getRegisteredUsersAsync(String iceP_filter, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.util.Map<Integer, String>> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getRegisteredUsers", com.zeroc.Ice.OperationMode.Idempotent, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_filter);
                 }, istr -> {
                     java.util.Map<Integer, String> ret;
                     ret = NameMapHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    /**
     * Set additional information for user registration.
     * @param id Userid of registered user.
     * @param info Information to set about user. This should be merged with existing information.
     * @return 1 for successful update, 0 for unsuccessful update, -1 to fall through.
     **/
    default int setInfo(int id, java.util.Map<UserInfo, String> info)
    {
        return setInfo(id, info, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    /**
     * Set additional information for user registration.
     * @param id Userid of registered user.
     * @param info Information to set about user. This should be merged with existing information.
     * @param context The Context map to send with the invocation.
     * @return 1 for successful update, 0 for unsuccessful update, -1 to fall through.
     **/
    default int setInfo(int id, java.util.Map<UserInfo, String> info, java.util.Map<String, String> context)
    {
        return _iceI_setInfoAsync(id, info, context, true).waitForResponse();
    }

    /**
     * Set additional information for user registration.
     * @param id Userid of registered user.
     * @param info Information to set about user. This should be merged with existing information.
     * @return 1 for successful update, 0 for unsuccessful update, -1 to fall through.
     **/
    default java.util.concurrent.CompletableFuture<Integer> setInfoAsync(int id, java.util.Map<UserInfo, String> info)
    {
        return _iceI_setInfoAsync(id, info, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    /**
     * Set additional information for user registration.
     * @param id Userid of registered user.
     * @param info Information to set about user. This should be merged with existing information.
     * @param context The Context map to send with the invocation.
     * @return 1 for successful update, 0 for unsuccessful update, -1 to fall through.
     **/
    default java.util.concurrent.CompletableFuture<Integer> setInfoAsync(int id, java.util.Map<UserInfo, String> info, java.util.Map<String, String> context)
    {
        return _iceI_setInfoAsync(id, info, context, false);
    }

    /**
     * @hidden
     * @param iceP_id -
     * @param iceP_info -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Integer> _iceI_setInfoAsync(int iceP_id, java.util.Map<UserInfo, String> iceP_info, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Integer> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "setInfo", com.zeroc.Ice.OperationMode.Idempotent, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeInt(iceP_id);
                     UserInfoMapHelper.write(ostr, iceP_info);
                 }, istr -> {
                     int ret;
                     ret = istr.readInt();
                     return ret;
                 });
        return f;
    }

    /**
     * Set texture (now called avatar) of user registration.
     * @param id registrationId of registered user.
     * @param tex New texture.
     * @return 1 for successful update, 0 for unsuccessful update, -1 to fall through.
     **/
    default int setTexture(int id, byte[] tex)
    {
        return setTexture(id, tex, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    /**
     * Set texture (now called avatar) of user registration.
     * @param id registrationId of registered user.
     * @param tex New texture.
     * @param context The Context map to send with the invocation.
     * @return 1 for successful update, 0 for unsuccessful update, -1 to fall through.
     **/
    default int setTexture(int id, byte[] tex, java.util.Map<String, String> context)
    {
        return _iceI_setTextureAsync(id, tex, context, true).waitForResponse();
    }

    /**
     * Set texture (now called avatar) of user registration.
     * @param id registrationId of registered user.
     * @param tex New texture.
     * @return 1 for successful update, 0 for unsuccessful update, -1 to fall through.
     **/
    default java.util.concurrent.CompletableFuture<Integer> setTextureAsync(int id, byte[] tex)
    {
        return _iceI_setTextureAsync(id, tex, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    /**
     * Set texture (now called avatar) of user registration.
     * @param id registrationId of registered user.
     * @param tex New texture.
     * @param context The Context map to send with the invocation.
     * @return 1 for successful update, 0 for unsuccessful update, -1 to fall through.
     **/
    default java.util.concurrent.CompletableFuture<Integer> setTextureAsync(int id, byte[] tex, java.util.Map<String, String> context)
    {
        return _iceI_setTextureAsync(id, tex, context, false);
    }

    /**
     * @hidden
     * @param iceP_id -
     * @param iceP_tex -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Integer> _iceI_setTextureAsync(int iceP_id, byte[] iceP_tex, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Integer> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "setTexture", com.zeroc.Ice.OperationMode.Idempotent, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeInt(iceP_id);
                     ostr.writeByteSeq(iceP_tex);
                 }, istr -> {
                     int ret;
                     ret = istr.readInt();
                     return ret;
                 });
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ServerUpdatingAuthenticatorPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), ServerUpdatingAuthenticatorPrx.class, _ServerUpdatingAuthenticatorPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ServerUpdatingAuthenticatorPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), ServerUpdatingAuthenticatorPrx.class, _ServerUpdatingAuthenticatorPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ServerUpdatingAuthenticatorPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), ServerUpdatingAuthenticatorPrx.class, _ServerUpdatingAuthenticatorPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ServerUpdatingAuthenticatorPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), ServerUpdatingAuthenticatorPrx.class, _ServerUpdatingAuthenticatorPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static ServerUpdatingAuthenticatorPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, ServerUpdatingAuthenticatorPrx.class, _ServerUpdatingAuthenticatorPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static ServerUpdatingAuthenticatorPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, ServerUpdatingAuthenticatorPrx.class, _ServerUpdatingAuthenticatorPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default ServerUpdatingAuthenticatorPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (ServerUpdatingAuthenticatorPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default ServerUpdatingAuthenticatorPrx ice_adapterId(String newAdapterId)
    {
        return (ServerUpdatingAuthenticatorPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default ServerUpdatingAuthenticatorPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (ServerUpdatingAuthenticatorPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default ServerUpdatingAuthenticatorPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (ServerUpdatingAuthenticatorPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default ServerUpdatingAuthenticatorPrx ice_invocationTimeout(int newTimeout)
    {
        return (ServerUpdatingAuthenticatorPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default ServerUpdatingAuthenticatorPrx ice_connectionCached(boolean newCache)
    {
        return (ServerUpdatingAuthenticatorPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default ServerUpdatingAuthenticatorPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (ServerUpdatingAuthenticatorPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ServerUpdatingAuthenticatorPrx ice_secure(boolean b)
    {
        return (ServerUpdatingAuthenticatorPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default ServerUpdatingAuthenticatorPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (ServerUpdatingAuthenticatorPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ServerUpdatingAuthenticatorPrx ice_preferSecure(boolean b)
    {
        return (ServerUpdatingAuthenticatorPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default ServerUpdatingAuthenticatorPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (ServerUpdatingAuthenticatorPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default ServerUpdatingAuthenticatorPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (ServerUpdatingAuthenticatorPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default ServerUpdatingAuthenticatorPrx ice_collocationOptimized(boolean b)
    {
        return (ServerUpdatingAuthenticatorPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default ServerUpdatingAuthenticatorPrx ice_twoway()
    {
        return (ServerUpdatingAuthenticatorPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default ServerUpdatingAuthenticatorPrx ice_oneway()
    {
        return (ServerUpdatingAuthenticatorPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default ServerUpdatingAuthenticatorPrx ice_batchOneway()
    {
        return (ServerUpdatingAuthenticatorPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default ServerUpdatingAuthenticatorPrx ice_datagram()
    {
        return (ServerUpdatingAuthenticatorPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default ServerUpdatingAuthenticatorPrx ice_batchDatagram()
    {
        return (ServerUpdatingAuthenticatorPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default ServerUpdatingAuthenticatorPrx ice_compress(boolean co)
    {
        return (ServerUpdatingAuthenticatorPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default ServerUpdatingAuthenticatorPrx ice_timeout(int t)
    {
        return (ServerUpdatingAuthenticatorPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default ServerUpdatingAuthenticatorPrx ice_connectionId(String connectionId)
    {
        return (ServerUpdatingAuthenticatorPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default ServerUpdatingAuthenticatorPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (ServerUpdatingAuthenticatorPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::Murmur::ServerUpdatingAuthenticator";
    }
}
