//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.9
//
// <auto-generated>
//
// Generated from file `Murmur.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package net.mstjr.murmur.helpers;

import net.mstjr.murmur.proxy.server.channel.Channel;

/**
 * Helper class for marshaling/unmarshaling ChannelMap.
 **/

public final class ChannelMapHelper
{
    public static void write(com.zeroc.Ice.OutputStream ostr, java.util.Map<Integer, Channel> v)
    {
        if(v == null)
        {
            ostr.writeSize(0);
        }
        else
        {
            ostr.writeSize(v.size());
            for(java.util.Map.Entry<Integer, Channel> e : v.entrySet())
            {
                ostr.writeInt(e.getKey());
                Channel.ice_write(ostr, e.getValue());
            }
        }
    }

    public static java.util.Map<Integer, Channel> read(com.zeroc.Ice.InputStream istr)
    {
        java.util.Map<Integer, Channel> v;
        v = new java.util.HashMap<Integer, Channel>();
        int sz0 = istr.readSize();
        for(int i0 = 0; i0 < sz0; i0++)
        {
            int key;
            key = istr.readInt();
            Channel value;
            value = Channel.ice_read(istr);
            v.put(key, value);
        }
        return v;
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<java.util.Map<Integer, Channel>> v)
    {
        if(v != null && v.isPresent())
        {
            write(ostr, tag, v.get());
        }
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Map<Integer, Channel> v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ChannelMapHelper.write(ostr, v);
            ostr.endSize(pos);
        }
    }

    public static java.util.Optional<java.util.Map<Integer, Channel>> read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            java.util.Map<Integer, Channel> v;
            v = ChannelMapHelper.read(istr);
            return java.util.Optional.of(v);
        }
        else
        {
            return java.util.Optional.empty();
        }
    }
}
