//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.9
//
// <auto-generated>
//
// Generated from file `Murmur.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package net.mstjr.murmur.helpers;

import net.mstjr.murmur.proxy.server.entities.Group;

/**
 * Helper class for marshaling/unmarshaling GroupList.
 **/
public final class GroupListHelper
{
    public static void write(com.zeroc.Ice.OutputStream ostr, Group[] v)
    {
        if(v == null)
        {
            ostr.writeSize(0);
        }
        else
        {
            ostr.writeSize(v.length);
            for(int i0 = 0; i0 < v.length; i0++)
            {
                Group.ice_write(ostr, v[i0]);
            }
        }
    }

    public static Group[] read(com.zeroc.Ice.InputStream istr)
    {
        final Group[] v;
        final int len0 = istr.readAndCheckSeqSize(7);
        v = new Group[len0];
        for(int i0 = 0; i0 < len0; i0++)
        {
            v[i0] = Group.ice_read(istr);
        }
        return v;
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Group[]> v)
    {
        if(v != null && v.isPresent())
        {
            write(ostr, tag, v.get());
        }
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, Group[] v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            GroupListHelper.write(ostr, v);
            ostr.endSize(pos);
        }
    }

    public static java.util.Optional<Group[]> read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            Group[] v;
            v = GroupListHelper.read(istr);
            return java.util.Optional.of(v);
        }
        else
        {
            return java.util.Optional.empty();
        }
    }
}
